{
  pkgs,
  lib,
  inputs,
  environment,
}:

let
  agentSandbox = inputs.agent-sandbox.lib.${pkgs.stdenv.hostPlatform.system};

  binName = "omp";
  omp = pkgs.writeShellScriptBin binName ''
    export PI_PROXY="$HTTPS_PROXY"
    ${configOverlays}
    exec ${pkgs.llm-agents.omp}/bin/${binName} "$@"
  '';

  configOverlays = ''
    export PI_CONFIG_FILES="$HOME/.omp/agent/autogenerated.yml"
    if [ -e "$HOME/.omp/agent/config.yml" ]; then
      export PI_CONFIG_FILES="$PI_CONFIG_FILES:$HOME/.omp/agent/config.yml"
    fi
  '';

  domains = import ./domains.nix { inherit lib; };
  paths = import ./paths.nix { inherit lib; };

  # Resolved at runtime by the wrapper's bash script (paths here are shell
  # strings, not Nix values) since the desktop user's uid varies per machine.
  waylandRuntimeDir = "/run/user/$(id -u)";
  waylandDisplay = "wayland-0";
  waylandSocketPath = "${waylandRuntimeDir}/${waylandDisplay}";

  sandboxedPackage = agentSandbox.mkSandbox {
    pkg = omp;
    inherit binName;
    outName = binName;

    allowedPackages = environment.path;
    allowedDomains = domains.allowed;

    allowNix = true;
    allowGpu = true;

    inherit (paths) rwDirs rwFiles;

    # Bind system nix config read-only so the agent inherits experimental
    # features (nix-command, flakes) and substituter/registry settings.
    roFiles = [ "/etc/nix/nix.conf" ] ++ paths.roFiles;
    roDirs = [ waylandSocketPath ] ++ paths.roDirs;

    env = environment.env // {
      # Lets the instruction extension detect sandboxed vs. -nosandbox
      # execution without relying on fragile process-name introspection.
      MDAROCHA_AGENT_SANDBOX = "1";
      # Puppeteer connects to Chrome's DevTools endpoint on 127.0.0.1
      # (sandbox-local loopback, isolated from the host). Without these,
      # Bun routes the WebSocket upgrade through HTTP_PROXY, which returns
      # 403 for 127.0.0.1 because it is not in the allowlist.
      NO_PROXY = "127.0.0.1,localhost";
      no_proxy = "127.0.0.1,localhost";
      # Chromium-based tests (e.g. Angular/Karma) call fontconfig to enumerate
      # fonts. Without a valid config file the sandbox sees no fonts and Chrome
      # aborts. Point at the Nix-provided fonts.conf so fontconfig initialises
      # correctly inside the sandbox.
      FONTCONFIG_FILE = "${pkgs.fontconfig.out}/etc/fonts/fonts.conf";
      # Expose to allow clipboard access
      WAYLAND_DISPLAY = waylandDisplay;
      XDG_RUNTIME_DIR = waylandRuntimeDir;
      # Evaluated on the host, where `gh` already has keyring access.
      GH_TOKEN = "$(${pkgs.gh}/bin/gh auth token)";
    };
  };

  # Same toolset and environment as the sandboxed variant, just without the
  # bwrap layer around it.
  hostPackage = pkgs.writeShellScriptBin "${binName}-nosandbox" ''
    export PATH="${lib.makeBinPath environment.path}:$PATH"
    ${lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "export ${name}=${lib.escapeShellArg value}") environment.env
    )}

    ${configOverlays}
    exec ${pkgs.llm-agents.omp}/bin/${binName} "$@"
  '';
in
{
  package = sandboxedPackage;
  package-nosandbox = hostPackage;

  inherit (paths) ensureDirs;

  instructions = import ./instructions.nix {
    inherit lib;
    domainList = domains.markdownList;
  };
}
