-- Solarized UI roles.
vim.o.background = "dark"
require("solarized").setup({})
vim.cmd.colorscheme("solarized")

local function apply_solarized_ui()
  local dark = vim.o.background == "dark"
  local p = dark and {
    canvas = "#002b36",
    panel = "#073642",
    line = "#0b3a42",
    muted = "#586e75",
    soft = "#657b83",
    text = "#839496",
    strong = "#93a1a1",
    blue = "#268bd2",
    cyan = "#2aa198",
    green = "#859900",
    yellow = "#b58900",
    orange = "#cb4b16",
    red = "#dc322f",
    violet = "#6c71c4",
  } or {
    canvas = "#fdf6e3",
    panel = "#eee8d5",
    line = "#d8d2c1",
    muted = "#93a1a1",
    soft = "#839496",
    text = "#657b83",
    strong = "#586e75",
    blue = "#268bd2",
    cyan = "#2aa198",
    green = "#859900",
    yellow = "#b58900",
    orange = "#cb4b16",
    red = "#dc322f",
    violet = "#6c71c4",
  }

  local highlights = {
    Normal = { fg = p.text, bg = p.canvas },
    NormalNC = { fg = p.text, bg = p.canvas },
    NormalFloat = { fg = p.text, bg = p.panel },
    FloatBorder = { fg = p.soft, bg = p.panel },
    WinSeparator = { fg = p.line, bg = p.canvas },
    VertSplit = { fg = p.line, bg = p.canvas },
    ColorColumn = { bg = p.line },
    CursorLine = { bg = p.panel },
    CursorLineNr = { fg = p.strong, bg = p.panel, bold = true },
    LineNr = { fg = p.muted, bg = p.canvas },
    SignColumn = { fg = p.muted, bg = p.canvas },
    FoldColumn = { fg = p.muted, bg = p.canvas },
    Visual = { bg = dark and "#0b4350" or "#d8e2df" },
    Search = { fg = p.canvas, bg = p.yellow },
    IncSearch = { fg = p.canvas, bg = p.orange },
    Pmenu = { fg = p.text, bg = p.panel },
    PmenuSel = { fg = p.strong, bg = p.line, bold = true },
    PmenuSbar = { bg = p.line },
    PmenuThumb = { bg = p.soft },
    StatusLine = { fg = p.text, bg = p.panel },
    StatusLineNC = { fg = p.muted, bg = p.panel },
    TabLine = { fg = p.muted, bg = p.panel },
    TabLineFill = { bg = p.canvas },
    TabLineSel = { fg = p.strong, bg = p.line, bold = true },
    Directory = { fg = p.blue },
    Title = { fg = p.strong, bold = true },
    Special = { fg = p.violet },
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.cyan },
    DiagnosticOk = { fg = p.green },
    DiagnosticVirtualTextError = { fg = p.red, bg = dark and "#3b252a" or "#f6d8d2" },
    DiagnosticVirtualTextWarn = { fg = p.yellow, bg = dark and "#393326" or "#f3e7c2" },
    DiagnosticVirtualTextInfo = { fg = p.blue, bg = dark and "#173e4b" or "#d7eaf4" },
    DiagnosticVirtualTextHint = { fg = p.cyan, bg = dark and "#173f40" or "#d5ece7" },
    SnacksIndent = { fg = p.line },
    SnacksIndentScope = { fg = p.soft },
    SnacksIndentChunk = { fg = p.line },
    SnacksNotifierMinimal = { fg = p.text, bg = p.panel },
    SnacksNotifierBorderInfo = { fg = p.blue, bg = p.panel },
    SnacksNotifierBorderWarn = { fg = p.yellow, bg = p.panel },
    SnacksNotifierBorderError = { fg = p.red, bg = p.panel },
    SnacksPickerInput = { fg = p.text, bg = p.panel },
    SnacksPickerList = { fg = p.text, bg = p.panel },
    SnacksPickerListCursorLine = { fg = p.strong, bg = p.line },
    SnacksPickerPrompt = { fg = p.cyan, bg = p.panel, bold = true },
    SnacksPickerMatch = { fg = p.yellow, bold = true },
    SnacksTerminal = { fg = p.text, bg = p.panel },
    SnacksTerminalTitle = { fg = p.cyan, bg = p.panel, bold = true },
    NvimTreeNormal = { fg = p.text, bg = p.panel },
    NvimTreeNormalNC = { fg = p.text, bg = p.panel },
    NvimTreeEndOfBuffer = { fg = p.panel, bg = p.panel },
    NvimTreeWinSeparator = { fg = p.line, bg = p.panel },
    NvimTreeCursorLine = { bg = p.line },
    NvimTreeFolderName = { fg = p.blue },
    NvimTreeOpenedFolderName = { fg = p.cyan, bold = true },
    NvimTreeEmptyFolderName = { fg = p.muted },
    NvimTreeRootFolder = { fg = p.strong, bold = true },
    NvimTreeFolderIcon = { fg = p.blue },
    NvimTreeIndentMarker = { fg = p.line },
    NvimTreeGitNew = { fg = p.green },
    NvimTreeGitDirty = { fg = p.orange },
    NvimTreeGitStaged = { fg = p.green },
    NvimTreeGitDeleted = { fg = p.red },
    NvimTreeGitMerge = { fg = p.violet },
    NvimTreeGitRenamed = { fg = p.cyan },
    NvimTreeGitIgnored = { fg = p.muted },
    NvimTreeLspDiagnosticsError = { fg = p.red },
    NvimTreeLspDiagnosticsWarning = { fg = p.yellow },
    NvimTreeLspDiagnosticsInformation = { fg = p.blue },
    NvimTreeLspDiagnosticsHint = { fg = p.cyan },
    NvimTreeDiagnosticError = { fg = p.red },
    NvimTreeDiagnosticWarn = { fg = p.yellow },
    NvimTreeDiagnosticInfo = { fg = p.blue },
    NvimTreeDiagnosticHint = { fg = p.cyan },
    AerialNormal = { fg = p.text, bg = p.panel },
    AerialLine = { bg = p.line },
    AerialGuide = { fg = p.line },
    AerialLineNC = { fg = p.muted, bg = p.panel },
    AerialFloatNormal = { fg = p.text, bg = p.panel },
    AerialFloatBorder = { fg = p.soft, bg = p.panel },
    AerialArrayIcon = { fg = p.violet },
    AerialBooleanIcon = { fg = p.orange },
    AerialClassIcon = { fg = p.yellow },
    AerialFunctionIcon = { fg = p.blue },
    AerialMethodIcon = { fg = p.cyan },
    AerialModuleIcon = { fg = p.violet },
    AerialVariableIcon = { fg = p.text },
    MiniClueBorder = { fg = p.soft, bg = p.panel },
    MiniClueTitle = { fg = p.strong, bg = p.panel, bold = true },
    MiniClueNextKey = { fg = p.cyan, bg = p.panel, bold = true },
    MiniClueNextKeyWithPostkeys = { fg = p.blue, bg = p.panel, bold = true },
    MiniClueDescGroup = { fg = p.strong, bg = p.panel },
    MiniClueDescSingle = { fg = p.text, bg = p.panel },
    MiniClueSeparator = { fg = p.muted, bg = p.panel },
    BufferLineFill = { bg = p.canvas },
    BufferLineBackground = { fg = p.muted, bg = p.panel },
    BufferLineBufferVisible = { fg = p.text, bg = p.panel },
    BufferLineBufferSelected = { fg = p.strong, bg = p.line, bold = true },
    BufferLineIndicatorSelected = { fg = p.blue, bg = p.line },
    BufferLineSeparator = { fg = p.panel, bg = p.canvas },
    BufferLineSeparatorVisible = { fg = p.panel, bg = p.canvas },
    BufferLineSeparatorSelected = { fg = p.line, bg = p.panel },
    BufferLineCloseButton = { fg = p.muted, bg = p.panel },
    BufferLineCloseButtonVisible = { fg = p.text, bg = p.panel },
    BufferLineCloseButtonSelected = { fg = p.red, bg = p.line },
    BufferLineModified = { fg = p.orange, bg = p.panel },
    BufferLineModifiedSelected = { fg = p.orange, bg = p.line },
    BufferLineError = { fg = p.red, bg = p.panel },
    BufferLineWarning = { fg = p.yellow, bg = p.panel },
    BufferLineInfo = { fg = p.blue, bg = p.panel },
    BufferLineHint = { fg = p.cyan, bg = p.panel },
    BlinkCmpMenu = { fg = p.text, bg = p.panel },
    BlinkCmpMenuBorder = { fg = p.soft, bg = p.panel },
    BlinkCmpMenuSelection = { fg = p.strong, bg = p.line },
    BlinkCmpLabelMatch = { fg = p.yellow, bold = true },
    BlinkCmpDoc = { fg = p.text, bg = p.panel },
    BlinkCmpDocBorder = { fg = p.soft, bg = p.panel },
    BlinkCmpKindFunction = { fg = p.blue },
    BlinkCmpKindMethod = { fg = p.cyan },
    BlinkCmpKindVariable = { fg = p.text },
    RenderMarkdownCode = { bg = dark and "#07313a" or "#eee8d5" },
    RenderMarkdownCodeInfo = { fg = p.muted, bg = dark and "#07313a" or "#eee8d5" },
    RenderMarkdownCodeBorder = { fg = p.line, bg = dark and "#07313a" or "#eee8d5" },
    RenderMarkdownCodeInline = { fg = p.cyan, bg = dark and "#07313a" or "#eee8d5" },
    RenderMarkdownBullet = { fg = p.cyan },
    RenderMarkdownTableHead = { fg = p.strong, bg = p.panel, bold = true },
    RenderMarkdownTableRow = { fg = p.text, bg = p.canvas },
    RenderMarkdownInfo = { fg = p.blue },
    RenderMarkdownSuccess = { fg = p.green },
    RenderMarkdownHint = { fg = p.cyan },
    RenderMarkdownWarn = { fg = p.yellow },
    RenderMarkdownError = { fg = p.red },
    RenderMarkdownQuote = { fg = p.violet },
    RenderMarkdownH1 = { fg = p.strong, bold = true },
    RenderMarkdownH2 = { fg = p.blue, bold = true },
    RenderMarkdownH3 = { fg = p.cyan, bold = true },
    RenderMarkdownH4 = { fg = p.green, bold = true },
    RenderMarkdownH5 = { fg = p.yellow, bold = true },
    RenderMarkdownH6 = { fg = p.violet, bold = true },
    RenderMarkdownH1Bg = { bg = dark and "#073640" or "#eee8d5" },
    RenderMarkdownH2Bg = { bg = dark and "#063943" or "#e8efe4" },
    RenderMarkdownH3Bg = { bg = dark and "#063b3e" or "#e4efed" },
    RenderMarkdownH4Bg = { bg = dark and "#123c31" or "#edf0dc" },
    RenderMarkdownH5Bg = { bg = dark and "#3b3524" or "#f3e7c2" },
    RenderMarkdownH6Bg = { bg = dark and "#2f3347" or "#e7e4f0" },
  }

  for group, spec in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, spec)
  end
end

apply_solarized_ui()
vim.api.nvim_create_autocmd("ColorScheme", {
  group = vim.api.nvim_create_augroup("mdarocha-solarized-ui", { clear = true }),
  callback = apply_solarized_ui,
})
