name: 📦️ Build configurations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@90bb610b90bf290cad97484ba341453bd1cbefea # v19

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@f6b84c9884c22039e1fc23dadb4a0d0add56c197 # v11

      - name: Setup Cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: mdarocha-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          # only push from the main branch
          skipPush: ${{ github.event_name == 'pull_request' }}

      - run: nix flake check -L

      - name: Report configuration sizes
        run: nix run .#report-sizes >> $GITHUB_STEP_SUMMARY
