name: 📦️ Build configurations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: mdarocha-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          # only push from the main branch
          skipPush: ${{ github.event_name == 'pull_request' }}

      - run: nix flake check -L

      - name: Report configuration sizes
        run: nix run .#report-sizes >> $GITHUB_SUMMARY
