name: 📦️ Build configurations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - name: Install Nix
        uses: mdarocha/nix-magic-setup@fbeadb287d13c1f3a3c2ccd9b7fb0f6201300997 # v1.3.0

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@de924abd783455e8429c858962b9e43062d19da1 # v13

      - name: Setup Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: mdarocha-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          # only push from the main branch
          skipPush: ${{ github.event_name == 'pull_request' }}

      - run: nix flake check -L

      - name: Report configuration sizes
        run: nix run .#report-sizes >> $GITHUB_STEP_SUMMARY
