{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:

let
  cfg = config.mdarocha.llm-agents;

  yaml = pkgs.formats.yaml { };

  defaultConfig = import ./config.nix { inherit config pkgs lib; };
  mergedConfig = lib.recursiveUpdate defaultConfig cfg.oh-my-pi.settings;

  filesIn =
    dir: suffix:
    lib.mapAttrs' (file: _: lib.nameValuePair (lib.removeSuffix suffix file) (dir + "/${file}")) (
      lib.filterAttrs (file: kind: kind == "regular" && lib.hasSuffix suffix file) (builtins.readDir dir)
    );

  rules = filesIn ./rules ".md";
  extensions = filesIn ./extensions ".ts";

  sandbox = import ./sandbox { inherit pkgs lib inputs; };

  ompSpecificInstructions = ''
    ## Git worktrees

    If you create git worktrees, always use the `~/.omp/wt` folder (the
    same folder the built-in `github` tool's `pr_checkout` op uses).

    Name each worktree directory `<slug>-<repo-hash>`, matching that same
    built-in convention (`<pr-number>-<repo-hash>`):
    - `<slug>`: a short, descriptive identifier for the work (issue/PR
      number, ticket id, or a brief kebab-case task descriptor) — not the
      branch name verbatim.
    - `<repo-hash>`: a 7-hex-character digest of the repository root path
      (e.g. `git rev-parse --show-toplevel | sha1sum | cut -c1-7`), so
      worktrees from different repos never collide inside the shared
      `~/.omp/wt` folder.
  '';
in
{
  options.mdarocha.llm-agents.oh-my-pi = {
    enable = lib.mkEnableOption "oh-my-pi";

    package = lib.mkOption {
      type = lib.types.package;
      default = sandbox.package;
      description = ''
        oh-my-pi agent package.
      '';
    };

    package-nosandbox = lib.mkOption {
      type = lib.types.package;
      default = sandbox.package-nosandbox;
      description = ''
        oh-my-pi agent package without sandboxing.
      '';
    };

    settings = lib.mkOption {
      default = { };
      type = yaml.type;
      description = ''
        oh-my-pi settings to deep-merge with the defaults.
      '';
    };
  };

  config = lib.mkIf cfg.oh-my-pi.enable {
    home.packages = [
      cfg.oh-my-pi.package
      cfg.oh-my-pi.package-nosandbox
    ];

    home.file = lib.mkMerge [
      {
        ".omp/agent/AGENTS.md".text = lib.concatStringsSep "\n" [
          cfg.instructions
          sandbox.instructions.toolset
          ompSpecificInstructions
        ];

        # NixOS lacks the FHS dynamic loader the generic release binary
        # needs, so oh-my-pi's runtime yt-dlp download is unusable here.
        ".omp/agent/tools/yt-dlp".source = "${pkgs.yt-dlp}/bin/yt-dlp";

        ".omp/agent/extensions/sandbox-instructions.ts".text = ''
          import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

          const SANDBOX = ${builtins.toJSON sandbox.instructions.sandboxed};
          const NO_SANDBOX = ${builtins.toJSON sandbox.instructions.host};

          export default function (pi: ExtensionAPI) {
            pi.setLabel("Sandbox Instructions");

            pi.on("before_agent_start", async (event) => {
              const extra = process.env.MDAROCHA_AGENT_SANDBOX === "1" ? SANDBOX : NO_SANDBOX;

              // The returned array replaces the prompt wholesale, so carry the
              // current one over instead of returning the chunk alone.
              return {
                systemPrompt: [...event.systemPrompt, extra],
              };
            });
          }
        '';

        ".omp/agent/autogenerated.yml".source = yaml.generate "omp-autogenerated.yml" mergedConfig;
      }
      (lib.mapAttrs' (
        name: dir: lib.nameValuePair ".omp/agent/skills/${name}" { source = dir; }
      ) cfg.skills)
      (lib.mapAttrs' (name: src: lib.nameValuePair ".omp/agent/rules/${name}.md" { source = src; }) rules)
      (lib.mapAttrs' (
        name: src: lib.nameValuePair ".omp/agent/extensions/${name}.ts" { source = src; }
      ) extensions)
    ];

    home.activation.ensureAgentSandboxDirs = lib.hm.dag.entryAfter [
      "writeBoundary"
    ] sandbox.ensureDirs;

    home.activation.download-omp-tiny-models =
      lib.mkIf
        (
          mergedConfig.providers ? tinyModel
          && mergedConfig.providers.tinyModel != null
          && mergedConfig.providers.tinyModel != "online"
        )
        (
          lib.hm.dag.entryAfter [ "writeBoundary" "reloadSystemd" ] ''
            run ${cfg.oh-my-pi.package-nosandbox}/bin/omp-nosandbox tiny-models download ${mergedConfig.providers.tinyModel}
          ''
        );
  };
}
