{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:

let
  cfg = config.mdarocha.llm-agents;

  yaml = pkgs.formats.yaml { };

  defaultConfig = import ./config.nix { inherit config pkgs lib; };
  mergedConfig = lib.recursiveUpdate defaultConfig cfg.oh-my-pi.settings;

  # `local/<model-id>[:suffix]` role selectors (tiny, memory, judge, ...) that need their weights
  # predownloaded; retired `providers.tinyModel` etc. migrate into `modelRoles` on load, so this
  # covers every local model role assignment, not just the tiny one.
  localModels = lib.unique (
    map (v: lib.removePrefix "local/" (lib.head (lib.splitString ":" v))) (
      lib.filter (v: lib.isString v && lib.hasPrefix "local/" v) (
        lib.attrValues (mergedConfig.modelRoles or { })
      )
    )
  );

  sandbox = import ./sandbox {
    inherit pkgs lib inputs;
    environment = cfg.environment;
  };

  ompSpecificInstructions = ''
    ## Git worktrees

    If you create git worktrees, always use the `~/.omp/wt` folder (the
    same folder the built-in `github` tool's `pr_checkout` op uses).

    Name each worktree directory `<slug>-<repo-hash>`, matching that same
    built-in convention (`<pr-number>-<repo-hash>`):
    - `<slug>`: a short, descriptive identifier for the work (issue/PR
      number, ticket id, or a brief kebab-case task descriptor) — not the
      branch name verbatim.
    - `<repo-hash>`: a 7-hex-character digest of the repository root path
      (e.g. `git rev-parse --show-toplevel | sha1sum | cut -c1-7`), so
      worktrees from different repos never collide inside the shared
      `~/.omp/wt` folder.

    ## Python execution environment

    The `eval` tool's Python kernel already runs inside the provisioned
    Nix environment, so no setup is needed before importing pre-installed
    packages there.
  '';
in
{
  options.mdarocha.llm-agents.oh-my-pi = {
    enable = lib.mkEnableOption "oh-my-pi";

    package = lib.mkOption {
      type = lib.types.package;
      default = sandbox.package;
      description = ''
        oh-my-pi agent package.
      '';
    };

    package-nosandbox = lib.mkOption {
      type = lib.types.package;
      default = sandbox.package-nosandbox;
      description = ''
        oh-my-pi agent package without sandboxing.
      '';
    };

    settings = lib.mkOption {
      default = { };
      type = yaml.type;
      description = ''
        oh-my-pi settings to deep-merge with the defaults.
      '';
    };
  };

  config = lib.mkIf cfg.oh-my-pi.enable {
    home.packages = [
      cfg.oh-my-pi.package
      cfg.oh-my-pi.package-nosandbox
    ];

    home.file = lib.mkMerge [
      {
        ".omp/agent/AGENTS.md".text = lib.concatStringsSep "\n" [
          cfg.instructions
          cfg.environment.instructions
          ompSpecificInstructions
        ];

        # NixOS lacks the FHS dynamic loader the generic release binary
        # needs, so oh-my-pi's runtime yt-dlp download is unusable here.
        ".omp/agent/tools/yt-dlp".source = "${pkgs.yt-dlp}/bin/yt-dlp";

        ".omp/agent/extensions/sandbox-instructions.ts".text = ''
          import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

          const SANDBOX = ${builtins.toJSON sandbox.instructions};
          const NO_SANDBOX = ${builtins.toJSON cfg.environment.hostInstructions};

          export default function (pi: ExtensionAPI) {
            pi.setLabel("Sandbox Instructions");

            pi.on("before_agent_start", async (event) => {
              const extra = process.env.MDAROCHA_AGENT_SANDBOX === "1" ? SANDBOX : NO_SANDBOX;

              // The returned array replaces the prompt wholesale, so carry the
              // current one over instead of returning the chunk alone.
              return {
                systemPrompt: [...event.systemPrompt, extra],
              };
            });
          }
        '';

        ".omp/agent/autogenerated.yml".source = yaml.generate "omp-autogenerated.yml" mergedConfig;
      }
      (lib.mapAttrs' (
        name: dir: lib.nameValuePair ".omp/agent/skills/${name}" { source = dir; }
      ) cfg.skills)
      (lib.mapAttrs' (
        name: src: lib.nameValuePair ".omp/agent/rules/${name}.md" { source = src; }
      ) cfg.rules)
    ];

    home.activation.ensureAgentSandboxDirs = lib.hm.dag.entryAfter [
      "writeBoundary"
    ] sandbox.ensureDirs;

    home.activation.download-omp-local-models = lib.mkIf (localModels != [ ]) (
      lib.hm.dag.entryAfter [ "writeBoundary" "reloadSystemd" ] (
        lib.concatMapStrings (model: ''
          ${cfg.oh-my-pi.package-nosandbox}/bin/omp-nosandbox tiny-models download ${lib.escapeShellArg model} \
            || echo "warning: failed to prefetch local model '${model}', continuing" >&2
        '') localModels
      )
    );
  };
}
